
services:
  saverdatabase:
    image: mariadb:11
    container_name: saver_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
    volumes:
      - saver_db_data:/var/lib/mysql
    networks:
      - saver_network

  saverapi:
    build: ./api
    container_name: saver_api
    restart: always
    depends_on:
      - saverdatabase
    environment:
      DB_HOST: ${db_host}
      DB_USER: ${db_user}
      DB_PASSWORD: ${db_password}
      DB_NAME: saver_db
      DB_PORT: ${DB_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - saver_network

  saverweb:
    build: ./web
    container_name: saver_web
    restart: always
    depends_on:
      - saverapi
    ports:
      - "8080:80"
    networks:
      - saver_network

networks:
  saver_network:
    driver: bridge

volumes:
  saver_db_data: